[versions]
gradle = "7.1.3"
kotlin = "1.6.10"
# https://github.com/pinterest/ktlint/releases
ktlint = "0.43.2"

# androidx version ref: https://developer.android.com/jetpack/androidx/explorer
androidx-core = "1.7.0"
androidx-appcompat = "1.4.1"
androidx-compose = "1.1.1"
androidx-material3 = "1.0.0-alpha10"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"

compose-accompanist = "0.23.1"

material = "1.5.0"

[libraries]
# for classpathes
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
oss-license-classpath = { module = "com.google.android.gms:oss-licenses-plugin", version = "0.10.4" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }

# Jetpack Compose
androidx-compose-ui-main = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
## tooling will be imported for only debug (debugImplementation in build.gradle)
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

# Jetpack Compose (Accompanist)
## https://github.com/google/accompanist/
compose-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "compose-accompanist" }
## https://coil-kt.github.io/coil/compose/
compose-coil = { module = "io.coil-kt:coil-compose", version = "1.4.0" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }

# core library dependency
tools-desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

oss-license-lib = { module = "com.google.android.gms:play-services-oss-licenses", version = "17.0.0" }

# test
test-junit = { module = "junit:junit", version = "4.13.2" }
test-androidx-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
test-androidx-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
test-androidx-compose-ui = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
test-truth = { module = "com.google.truth:truth", version = "1.1.3" }

[bundles]
android-base = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "android-material"
]
androidx-compose = [
    "androidx-compose-ui-main",
    "androidx-compose-ui-preview",
    # "androidx-compose-material",
    "androidx-compose-material3",
    "androidx-activity-compose"
]
compose-accompanist = [
    "compose-accompanist-insets",
    # coil is no longer a part of accompanist. but was a ex-part of it.
    "compose-coil"
]
androidx-lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-livedata-ktx"
]
[plugins]
spotless = { id = "com.diffplug.spotless", version = "5.14.3" }
gradle-versions-management = { id = "com.github.ben-manes.versions", version = "0.39.0" }
